### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by laserson** [psathyrella/ham#15]
I'm trying to build on my macOS machine, and I'm getting this error:

```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o _build/hample.o -c -Ofast -std=c++11 -Wall -Wextra -pedantic -DEPS=1e-6 -DPI=3.1415926535897932 -DSIZE_MAX=\(\(size_t\)-1\) -DSTATE_MAX=500 -Iinclude -Iyaml-cpp/include _build/hample.cc
g++ -o _build/args.o -c -Ofast -std=c++11 -Wall -Wextra -pedantic -DEPS=1e-6 -DPI=3.1415926535897932 -DSIZE_MAX=\(\(size_t\)-1\) -DSTATE_MAX=500 -Iinclude -Iyaml-cpp/include _build/args.cc
_build/args.cc:24:75: error: use of undeclared identifier 'INFINITY'
  logprob_ratio_threshold_arg_("", "logprob-ratio-threshold", "", false, -INFINITY, "float"),
                                                                          ^
1 error generated.
scons: *** [_build/args.o] Error 1
scons: building terminated because of errors.
```

I'm not familiar with scons so I'm hoping there may be an obvious fix here.  One suspicion is that `g++` is linked to clang. I tried setting `CC=/path/to/gcc` as an environment variable but I'm not sure that it took.

**Comment by psathyrella** [comment]
hm, that's weird. I don't know anything about whether clang should work, but INFINITY is defined in math.h, which is included in a number of files in packages/ham, so it should be defined.

As far as scons, [this](https://github.com/psathyrella/ham/blob/master/src/SConscript#L5) line imports the shell environment, which you can check by adding `print os.getenv('CC')`. But note that if you're building with, say, `./bin/build.sh` from partis, you'll probably need to adjust the environment within `./bin/build.sh`, not the shell that calls it.

Another approach would be to add INFINITY to the CPPDEFINES line in that same SConscript -- I'm not particularly wedded to the current approach, which was inherited from stochhmm.

**Comment by laserson** [comment]
Can you elaborate on the last suggestion?

**Comment by psathyrella** [comment]
changing [this](https://github.com/psathyrella/ham/blob/master/src/SConscript#L9) line to:

`env.Append(CPPDEFINES={'STATE_MAX':'500', 'SIZE_MAX':'\(\(size_t\)-1\)', 'PI':'3.1415926535897932', 'EPS':'1e-6', 'INFINITY':'1e15'})`

seems to work ok. I would like to know more about why clang doesn't recognize INFINITY before declaring this the best solution, and `1e15` is almost certainly a poor choice... but it passes the cursory tests, so it should be ok for a short term fix.

**Comment by laserson** [comment]
So actually, just adding

```
#include <cmath>
```

in `args.h` lets me move forward past that error.

**Comment by psathyrella** [comment]
huh, weird. I seem to recall that different compilers have different rules for resolving recursive includes, and while this certainly isn't recursive, I guess they could have different rules for less pathologic includes. In any case, thanks for the fix, I've just pushed it to master.

**Comment by laserson** [comment]
Thanks! Now I gotta fix a linker issue :P
