### ISSUE TITLE
Scons can't find sources supplied by env.Library() in src/SConscript 

### ISSUE THREAD

**Issue by ressy** [psathyrella/ham#16]
I'm completely new to Scons, so I could be missing something basic here, but when I try `scons bcrham` (as part of a partis install) it gives me this error like this:

```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o _build/bcrham.o -c -Ofast -std=c++11 -Wall -Wextra -pedantic -DEPS=1e-6 -DPI=3.1415926535897932 -DSIZE_MAX=\(\(size_t\)-1\) -DSTATE_MAX=500 -Iinclude _build/bcrham.cc
scons: *** [.../partis/packages/ham/_build/args.o] Source `.../partis/packages/ham/_build/args.cc' not found, needed by target `.../partis/packages/ham/_build/args.o'.
scons: building terminated because of errors.
```

It looks like Scons typically likes to copy everything from the src dir into the build dir, but ham skips that with `duplicate=0` in SConstruct and then gathers up the .cc files in src/SConscript and references them relative to the build dir.  But those files *aren't* in the build dir so I'm thinking maybe that's why Scons can't find them.

If I swap out this line in src/SConscript:

    sources.append(fname.replace('src/', '_build/'))

With this:

    sources.append(fname)

...it seems to run OK and I get a compiled bcrham executable.

This is from an attempted from-scratch partis install, using conda-supplied python and scons:

```
$ scons --version
SCons by Steven Knight et al.:
        script: v3.1.1.72ae09dc35ac2626f8ff711d8c4b30b6138e08e3, 2019-08-08 14:50:06, by bdeegan on octodog
        engine: v3.1.1.72ae09dc35ac2626f8ff711d8c4b30b6138e08e3, 2019-08-08 14:50:06, by bdeegan on octodog
        engine path: ['/home/jesse/miniconda3/envs/example-partis/lib/python2.7/site-packages/SCons']
Copyright (c) 2001 - 2019 The SCons Foundation
$ python --version
Python 2.7.18 :: Anaconda, Inc.
```

**Comment by psathyrella** [comment]
Hmm i haven't run plain `scons bcrham` in years, is there a reason you're not running bin/build.sh from the partis main dir? In either case this sounds to be me like what would happen if scons ran in the wrong dir?

**Comment by ressy** [comment]
Sorry, I should have clarified that-- I *was* running the build script from partis, but it gave me that error, so I started digging into the ham build step to try to narrow it down.  This is what I see starting from the main partis directory:

```
$ ./bin/build.sh 

--> running ./bin/build.sh

--> building ig-sw
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
gcc -o ig_align.o -c -std=gnu99 -Ofast -Wall -Wextra -pedantic -I. -Itclap ig_align.c
gcc -o ksw.o -c -std=gnu99 -Ofast -Wall -Wextra -pedantic -I. -Itclap ksw.c
ksw.c: In function ‘push_cigar’:
ksw.c:464:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (*n_cigar == 0 || op != (cigar[(*n_cigar) - 1]&0xf)) {
                          ^
gcc -o kstring.o -c -std=gnu99 -Ofast -Wall -Wextra -pedantic -I. -Itclap kstring.c
kstring.c: In function ‘kvsprintf’:
kstring.c:15:12: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (l + 1 > s->m - s->l) {
            ^
g++ -o ig_align_main.o -c -I. -Itclap ig_align_main.cpp
g++ -o ig-sw -Ofast ig_align.o ksw.o kstring.o ig_align_main.o -lz -lpthread
scons: done building targets.

--> building ham
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o _build/bcrham.o -c -Ofast -std=c++11 -Wall -Wextra -pedantic -DEPS=1e-6 -DPI=3.1415926535897932 -DSIZE_MAX=\(\(size_t\)-1\) -DSTATE_MAX=500 -Iinclude _build/bcrham.cc
scons: *** [/home/jesse/dev/examples/example-partis/partis/packages/ham/_build/args.o] Source `/home/jesse/dev/examples/example-partis/partis/packages/ham/_build/args.cc' not found, needed by target `/home/jesse/dev/examples/example-partis/partis/packages/ham/_build/args.o'.
scons: building terminated because of errors.
```

Does it work for you?  I wonder if some subtle difference in my versions of things is throwing it off.  (That, or a goof-up in what directory I'm in when, like you said... though I think I'm in the right place.)

Thanks for the quick response!

**Comment by psathyrella** [comment]
Yeah it works fine in my scratch builds, and the docker builds on our machines and dockerhub/quay. I imagine some version of something is different, and that's changing some behavior. It sounds like you've got it working atm, so I'll just add to my queue to see if i can change to your suggestion ^ without breaking anything else. It's for sure possible I did something silly/suboptimal in the scons file, but I have zero memory of how it works now since it was so long ago.

**Comment by ressy** [comment]
Gotcha, I know how that goes.  Yeah I have a working partis install inside a conda environment now, so there's no urgency from my side.  And feel free to close this if you aren't able to reproduce it.  If it helps, the conda environment YAML I'm using and the resulting set of packages are:

[environment.yml](https://github.com/psathyrella/ham/files/8092172/environment.yml.txt)
[pkgs.txt](https://github.com/psathyrella/ham/files/8092168/pkgs.txt)

**Comment by psathyrella** [comment]
well it works fine for me without the str replace, so i just switched it https://github.com/psathyrella/partis/commit/220cb79682e052d639af02b04c446758a5bb95d3

**Comment by psathyrella** [comment]
ok switched from ham subtree to submodule and updated this repo so it actually shows up here: https://github.com/psathyrella/ham/commit/2eaed8419da8071da9f35266a8dea374c454a5bb
